import Head from 'next/head'
import Header from '../components/Header'
import Entry from '../components/Entry'
import { useRef } from 'react'
import Title from '../components/Title'

const CreateEntry: React.FC = ({}) => {

  const titleRef = useRef<HTMLInputElement>(null);

  return (
    <div>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Title titleRef = { titleRef }/>
      <Entry titleRef = {titleRef}/>

    </div>
  )
}

export default CreateEntry;
