import Head from 'next/head'
import Header from '../components/Header'
import Entry from '../components/Entry'
import { useRef } from 'react'
import Title from '../components/Title'

const CreateEntry: React.FC = ({}) => {

  const titleRef = useRef<HTMLInputElement>(null);

  return (
    <div>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <div className = 'flex flex-col items-center w-full'>
        <div className = 'text-3xl font-mono p-5 w-full'>
          <Title titleRef = { titleRef }/>
        </div>
        <div className='w-full mt-5'>
          <Entry titleRef = {titleRef}/>
        </div>
      </div>

    </div>
  )
}

export default CreateEntry;
