import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import title component
import Header from '../components/Header'
//import entry component
import Entry from '../components/Entry'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Entry />

    </div>
  )
}
